[http_server]
sockets = ["127.0.0.1:8080"]
insecure_http = false
private_key = "/host.key"
certificate = "/host.crt"

[attestation_token]
extra_teekey_paths = ["/opt/confidential-containers/kbs/repository/tee_pubkey.pem", "/opt/confidential-containers/kbs/repository/gcp_tee_pubkey.pem"]
insecure_key = true

[attestation_service]
type = "coco_as_builtin"
work_dir = "/opt/confidential-containers/attestation-service"
policy_engine = "opa"

[attestation_service.attestation_token_broker]
type = "Ear"
duration_min = 5

[attestation_service.rvps_config]
type = "BuiltIn"

[policy_engine]
policy_path = "/opt/confidential-containers/opa/policy.rego"

[admin]
insecure_api = false
auth_public_key = "/public.pub"

[[plugins]]
name = "resource"
type = "LocalFs"
dir_path = "/opt/confidential-containers/kbs/repository"
